### ISSUE TITLE
Giving options in Settings don't allow a direct "Back" option.

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzman#1046]
## Steps to Reproduce
1. Sign in to your profile in the app.
2. Go to Settings.
3. Click "Scheduled Contributions" or any other give related setting.
4. Notice that the menu still shows instead of a back arrow option.
### Buggy Behavior

There is no back arrow option on giving options in Settings. Instead the main menu options still show. This is janky for our users because (a) it's inconsistent with the other setting options and (b) they have to then tap twice more to get back to where they were.
### Expected Behavior

The giving options in Settings should have a back arrow option to take the user back to the Settings menu.

**Comment by jbaxleyiii** [comment]
@richarddubay thanks for reporting this!

@samclaridge I think we need to talk through some parts of this

**Comment by briankalwat** [comment]
Confirmed on iPhone 7 running 10.0.1.
