### ISSUE TITLE
Giving history filters reset after viewing a receipt

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#1062]
## Steps to Reproduce
1. Visit Sections > Give > Giving History
2. Click the filter transactions section and add a date range (or simply filter by a person)
3. From the filtered list, click a card/receipt
4. Click the back arrow.
### Buggy Behavior

All filters reset to their default state. This happens whether a date range was entered or simply one person was selected.
### Expected Behavior

User should be returned to the filterest results list where they left off. Filters should not be reset.

**Comment by jbaxleyiii** [comment]
@jonhorton to do this we will need to expand our app global state storage. Are you okay with this being part of giving 1.1 instead of launch?

Also, nitpicky, but would this be an enhancement not a bug? (it's debatable for sure)

**Comment by jonhorton** [comment]
@jbaxleyiii waiting for giving 1.1 works for me instead of launch, just as long as we fix it shortly! 

I think I'd still consider this a bug since most users would either expect it to save the state (like going back on pagination) or get frustrated at having to constantly retype date ranges.

**Comment by jbaxleyiii** [comment]
👍 can do1

**Comment by meredithrouse** [comment]
SYS-3961
