### ISSUE TITLE
Locations/Series Page: Focus on Slider Breaks Navigation

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1073]
Could be related to #1075. Widespread issue with input focus + navigation functionality?

_This is also prevalent with the sermons slider on the sermon page._
## Steps to Reproduce

I've only been able to reproduce this on devices running iOS 10.
1. Go to the `Locations` section.
2. Tap on the first campus below (without releasing).
3. Scroll to the bottom of the page.
4. Press (and hold) on the first campus.
5. Swipe left or right and release.
### Buggy Behavior

The focus being on the campus slider has rendered the navigation useless. (I believe the slider is actually on top of the navigation and thus it renders it unusable.) Focusing on the search field at this point will make the navigation usable again.
### Expected Behavior

Navigation should always be usable.

**Comment by briankalwat** [comment]
Replicated this on iPhone 5s, 6 & 7.

**Comment by meredithrouse** [comment]
SYS-3962
