### ISSUE TITLE
Group Profile: Back Button Not Functioning After Onboarding Message Is Edited

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1075]
Could be related to #1073. Widespread issue with input focus + navigation functionality?
## Steps to Reproduce

I've only been able to reproduce this on devices running iOS 10.
1. View any group profile page.
2. Tap `Join Group`
3. Tap and Edit Message
4. Tap `Cancel`
5. Tap Back Button
### Buggy Behavior

Back button/navigation does not function.
### Expected Behavior

Back button/navigation should always function properly.

**Comment by edolyne** [comment]
It looks like we may need to add `.blur()` to the text areas associated with the form when clicking cancel.

**Comment by edolyne** [comment]
This is only happening on iOS, and can not be replicated via the simulator at this time.  It appears that our inputs & text areas are not hooking into native iOS bindings. 

This will need to be a post launch fix.

**Comment by briankalwat** [comment]
@edolyne I've had this happen on iPhone 5s, 6 & 7. When it does happen, it prevents you from moving between sections of the app completely.
