### ISSUE TITLE
Group Finder Results: Ellipses is not initially visible in "more" tag when lots of tags are selected

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1077]
## Steps to Reproduce

Describe how to reproduce this issue.
1. Tap the Group Finder in Navigation.
2. Tap to select 4-5 different tags.
3. Tap `Let's Go`.
4. Scroll through tags to the last tag.
### Buggy Behavior

The `more` tag initially does not have the ellipses in the tag.
### Expected Behavior

The `more` tag should always have the ellipses in the tag.
### Screenshots

![img_0083](https://cloud.githubusercontent.com/assets/2465823/18538284/55baebc6-7ada-11e6-956a-ff93e32ed3dd.PNG)

**Comment by colemanben** [comment]
I have the same issue with iPad Mini

**Comment by richarddubay** [comment]
iPad Air too. But works on the Nexus 7.

**Comment by morgansmithh** [comment]
I have same issue with Iphone 6+

**Comment by briankalwat** [comment]
Same with iPhone 7.
