### ISSUE TITLE
Music Player Repeat One Doesn't Repeat (Nexus 7) (iPad Air)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzman#1079]
## Steps to Reproduce
1. Go to an album.
2. Start playing a song.
3. Click the repeat button twice so that it says "One".
4. Move the slider to near the end of the song (which is kind of janky on iPad, fwiw).
5. When the song ends, it stays on the same song, and it isn't "paused", but the song won't play again until you click the play button to stop and start the music again.
### Buggy Behavior

The music player won't repeat the one song option.
### Expected Behavior

If I choose to repeat one song it should repeat continuously.

**Comment by jbaxleyiii** [comment]
I can confirm this on Nexus 5x. It's the only music feature that doesn't work on Android

**Comment by briankalwat** [comment]
@jbaxleyiii this is still broken in the latest beta on iOS 10.0.1.
