### ISSUE TITLE
Review Gift slide out is dark (Nexus 7)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzman#1084]
## Steps to Reproduce
1. Sign in to your account.
2. Go to the give page.
3. Add in an amount to give.
4. Click "Review Using ####"
5. The slide out has a dark color background.
### Buggy Behavior

The "Review Gift" slide out has a dark background.
### Expected Behavior

The "Review Gift" slide out should have a light background. Not sure if this is a problem or a config setting somewhere. If it's a setting, the dark background setting needs some styling to make it more readable.
### Screenshots

![46457531725194281-account_id 2](https://cloud.githubusercontent.com/assets/3229463/18549610/87b3d4b0-7b1d-11e6-86e0-577fcf163046.png)

**Comment by jbaxleyiii** [comment]
This is probably because modals in app are janky sometimes. Not something we will be able to fix for launch.

Couldn't replicate in other tests on device on in browser

**Comment by jonhorton** [comment]
@richarddubay @jbaxleyiii Sometimes I've seen this when the app hot updates and causes this.

**Comment by johnthepink** [comment]
I think this may have something to do with triggering a modal that is dark, and then triggering one that is not. Our ListDetail view is a dark modal, which is the view when you tap "..." next to a track our on the music player. https://github.com/NewSpring/Holtzmann/blob/master/imports/pages/music/music.ListDetail.js

Check that modals are properly handling their background colors.
