### ISSUE TITLE
Series Page: 'X' in Player Does Not Close Player

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1094]
## Steps to Reproduce
1. Go to any series page that has a trailer.
2. Play the trailer.
3. Tap `Done`.
4. If the fullscreen icon is visible instead of the 'X', tap the play icon to resume trailer.
5. Tap `Done`.
6. Tap 'X' to try to close the player.
### Buggy Behavior

Player does not close when 'X' is tapped.
### Expected Behavior

Tapping the 'X' should close the player, or it should not be visible if we're relying on the `Close the Trailer` cta below.
### Screenshots

![img_0084](https://cloud.githubusercontent.com/assets/2465823/18552427/646b5688-7b2a-11e6-9997-346844f6ddf7.PNG)

**Comment by briankalwat** [comment]
@JakeDawkins I believe this is happening anywhere there's a video. It's also happening on stories.

**Comment by jbaxleyiii** [comment]
After some digging, the x isn't actually meant to close the video. It is meant to close the fullscreen which iOS already did. This may go away with iOS 10 or we may have to fix ooyala's player.

Just iOS

**Comment by briankalwat** [comment]
This was surfaced on an iPhone 6s running iOS 10.0.1, fwiw.

**Comment by richarddubay** [comment]
@jbaxleyiii it's definitely there on iOS 10. Testing on the iPhone 5S with 9.3.5 shows a square in the bottom right-hand corner, which takes the video full screen on a tablet. Not sure what this means, but more info, right?

**Comment by johnthepink** [comment]
The first thing I'd try is updating the ooyala player here https://github.com/NewSpring/Holtzmann/blob/master/imports/index.js#L22-L31

We are currently at 4.6.9, and it looks like at least 4.7.8 is available per here https://github.com/ooyala/html5-skin#examples

But make sure to test all video related things after doing this. Last time I updated ooyala it broke our icon system.

**Comment by meredithrouse** [comment]
SYS-3964
