### ISSUE TITLE
Button Hover/Focus States Should Be Disabled on Mobile

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1096]
## Steps to Reproduce
1. Go to any series page that has a trailer.
2. Play the trailer.
3. Close the trailer.
### Buggy Behavior

Play/Close Trailer CTA has a filled, focus state that is intended for the hover state on desktop that doesn't translate to mobile.
### Expected Behavior

Buttons should have a consistent state on mobile.
### Screenshots

![img_0085](https://cloud.githubusercontent.com/assets/2465823/18552620/29d48ade-7b2b-11e6-8083-ca6d3bb4b80d.PNG)

**Comment by meredithrouse** [comment]
SYS-4083
