### ISSUE TITLE
Album Page: Navigation is Missing After Viewing Track Details from Audio Player

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1113]
## Steps to Reproduce

iPhone 6s on iOS 10.0.1
1. Go to any album page.
2. Play a song.
3. Open the Audio Player.
4. Tap '...' for track details.
5. Close track details.
6. Collapse Audio Player.
### Buggy Behavior

Album page navigation is missing, making it impossible to return to the main music feed.
### Expected Behavior

Album page nav should persist while user is on the album page.
### Screenshots

Expected Behavior:

![img_0093](https://cloud.githubusercontent.com/assets/2465823/18563434/987732e6-7b55-11e6-888c-e3f9ae7af8cb.PNG)

Actual Behavior, after interacting with the `...` in the audio player:

![img_0092 2](https://cloud.githubusercontent.com/assets/2465823/18563454/ac44d88c-7b55-11e6-9acc-f03bbbb6b4d6.PNG)

**Comment by jbaxleyiii** [comment]
This is a much more involved fix sadly. I don't think we will be able to get it into launch
