### ISSUE TITLE
Give: Stopping a schedule doesn't visually remove it immediately

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#1118]
I believe this is baked into our currently system, so I wanted to propose that we find a way to make actions (especially give) reflect immediately. Currently when I stop a schedule, the schedule still displays for a while in the active schedules section, and upon clicking into it, the "Stop Contribution" link is still available. This leads me to believe that the schedule I stopped is still active, even though it isn't.
## Steps to Reproduce
1. Create a schedule, or go to an existing one
2. click into the schedule card
3. Click stop contribution link
4. Go back to the active schedules list
### Buggy Behavior

The recently stopped schedule is still listed
Clicking into the recently stopped schedule, still has a stop contribution link as if the schedule were still active.
### Expected Behavior

Schedule is immediately removed from the UI

**Comment by jbaxleyiii** [comment]
@jonhorton with the move of giving to Heighliner this (and all giving actions) will show up correctly 👍
