### ISSUE TITLE
Background Audio

### ISSUE THREAD

**Issue by delianides** [NewSpring/Holtzman#1130]
### Buggy Behavior

the app doesn't play audio in the background without crashing.
### Expected Behavior

the app should play background audio.

**Comment by delianides** [comment]
when I updated the cordova media plugin to 2.4.0 the app no longer crashes but the background advancing always skips a song.  It seems like the playhead doesn't update fast enough before the song advances so it appears to skip a song.

**Comment by johnthepink** [comment]
@delianides interesting. We could also try installing from master, though the changes since 2.4.0 seem to only be documentation related.

**Comment by jbaxleyiii** [comment]
the scrubber work that @edolyne is doing may fix this?

**Comment by jbaxleyiii** [comment]
@delianides is this fixed now?

**Comment by johnthepink** [comment]
we have a separate issue for going to the next song so i think we can close this
