### ISSUE TITLE
The < character is untypable in a password input

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#1162]
## Steps to Reproduce

There's currently a bug (confirmed on Android) that prevents only the < character from being typed. The > character works, as well as all other special chars that I tested.
1. Open the app and go to the Profile section
2. try typing a < character into a password field
### Buggy Behavior

It's currently impossible to enter a < character.
This is preventing some people from signing in if they use that character within a password.
It only seems to be impacting the password field!
### Expected Behavior

The < character and other special characters should be allowed.

Related to WR-1924

**Comment by jbaxleyiii** [comment]
@jon this is due to our whitelist to prevent XSS injection I think. I'd much rather tell people not to use that character. Is that an option

**Comment by johnthepink** [comment]
I would be on the side of finding a way to enable the use of special characters, if only for the password field. It's pretty difficult to get people to use passwords that are actually secure. I wouldn't want to discourage them from using `<` if that's part of the way they make their password more secure.

I could look in to this some more, but I think adjusting to prevent actual tags, instead of things that look like tags, could be a way we improve this?

**Comment by jbaxleyiii** [comment]
@johnthepink I see your point about the password field. We could disable the usage of the striptags code on that field or anything where `type="password"`

**Comment by jonhorton** [comment]
Since we don't currently have a way to set password restrictions like that
in rock (or haven't currently enforced any) I think it would be helpful to
allow these characters. The specific issue was related to a staff member
who had a current password set using that character.

If @jbaxleyiii's suggestion of just on pw inputs works, let's go for it.

Would that be feasible for the next build?

On Sep 21, 2016 9:12 AM, "James Baxley" <notifications@github.com> wrote:

@johnthepink <https://github.com/johnthepink> I see your point about the
password field. We could disable the usage of the striptags code on that
field or anything where type="password"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NewSpring/Holtzmann/issues/1162#issuecomment-248607763>,
or mute the thread
