### ISSUE TITLE
Home feed meta title is set to Welcome

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#1168]
## Steps to Reproduce
1. Visit the app home feed
2. Inspect the meta data
### Buggy Behavior

The title is Welcome | NewSpring Church.

In Google Analytics it also appears like there isn't a distinction between /welcome and the / home feed.
### Expected Behavior

The title is Home Feed | NewSpring Church to help with better Google Analytics.
The url segment of /welcome should only apply to the first time welcome screen

**Comment by jonhorton** [comment]
On further investigation, it looks like Welcome is set as the title for many of the pages, including sections, discover, etc, instead of the corresponding title.

**Comment by jonhorton** [comment]
Here is what we're seeing related to urls in Google Analytics, which makes getting solid data extremely difficult!
![screen shot 2016-09-25 at 9 28 59 am](https://cloud.githubusercontent.com/assets/619297/18815533/ad93f470-8302-11e6-9832-79c271c463c9.png)

**Comment by jbaxleyiii** [comment]
@jonhorton I'm hoping / thinking we can get this into the next shipped build!

**Comment by jonhorton** [comment]
That would be AMAZING. :yay: :)

**Comment by jonhorton** [comment]
Also I love the @next label!
