### ISSUE TITLE
Sometimes meta data is set to undefined

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#1169]
## Steps to Reproduce

I'm not sure what is causing this, but I see it alot in Google Analytics. It seems like it's related to Group Finder perhaps?

https://www.dropbox.com/s/18patryiiabhpr5/Screenshot%202016-09-21%2012.08.57.png?dl=0

**Comment by jbaxleyiii** [comment]
Will be fixed when https://github.com/NewSpring/Holtzmann/issues/1168 is done
