### ISSUE TITLE
Next button has a tendency to skip to the song AFTER the next song. (Android)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzman#1209]
## Steps to Reproduce
1. Play a song.
2. Click the next button.
3. Watch it skip two songs.
### Buggy Behavior

Tapping the next button is moving to the song AFTER the next song.
### Expected Behavior

Tapping the next button should only move forward one song.

**Comment by jbaxleyiii** [comment]
@richarddubay is this only s4?

**Comment by richarddubay** [comment]
@jbaxleyiii This is also happening on the S5. So all Android.

**Comment by jbaxleyiii** [comment]
@JakeDawkins can you take this this afternoon?
