### ISSUE TITLE
Can play multiple songs at once. (Galaxy S4 & S5)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzman#1210]
## Steps to Reproduce
1. Play a song.
2. Tap another song.
3. They are both playing with no way to stop both of them from playing. 
### Buggy Behavior

The app is allowing you to play more than one song at once. Now that we allow the audio to play even with the app shut off, there is no way to stop the audio without shutting off the phone.
### Expected Behavior

When I choose a different track, it should stop playing the current playing track and play the one that was tapped.

**Comment by richarddubay** [comment]
This happens with sermons too fwiw.

**Comment by jbaxleyiii** [comment]
@JakeDawkins can you take this this afternoon?
