### ISSUE TITLE
Repeat One doesn't want to move on to next song. (iPhone 6)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzman#1211]
## Steps to Reproduce
1. Play a song.
2. Tap Repeat until you end up on Repeat One
3. Scrub or play the song until the end. The song doesn't move back to the start.
### Buggy Behavior

Repeat One won't go back to the beginning of the song.
### Expected Behavior

Repeat One would continuously repeat the same song over and over.

**Comment by jbaxleyiii** [comment]
@edolyne  can you take this this afternoon?
