### ISSUE TITLE
Devotional At Bottom

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Holtzman#1334]
## Steps to Reproduce

This bug is present in iOS on iPad
1. Scroll to the bottom of a devotional
2. Select a related devotional from the list
### Buggy Behavior

New devotional is loaded, and the user is not scrolled back to the top.
### Expected Behavior

When new devotional is loaded, the user is scrolled back to the top

**Comment by johnthepink** [comment]
This seems to be related the fact that the route change isn't triggering a new component render. It's just passing in the new props to the existing DevotionalSingle component.
