### ISSUE TITLE
Share Button Load Time

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Holtzman#1335]
## Steps to Reproduce

This bug is present in iOS on iPad
1. Open a piece of content that is shareable
2. Click the sharing icon
### Buggy Behavior

After pressing the share button, the share menu takes 3/4 of a second to load and appears broken.
### Expected Behavior

Time to share is decreased, or a visual loading state is added.

**Comment by johnthepink** [comment]
@edolyne was this produced on the iPad mini?
