### ISSUE TITLE
Music player cuts off related content 

### ISSUE THREAD

**Issue by JakeDawkins** [NewSpring/Holtzman#1343]
## Steps to Reproduce
1. Play any music
2. Go to a devotional
3. Go to the related content section at the bottom of the page
### Buggy Behavior

The bar cuts off the bottom of the related content section
### Expected Behavior

There should be margin below that section so none of it is cut off
### Screenshots

![screenshot 2016-10-09 16 46 01](https://cloud.githubusercontent.com/assets/9259509/19223554/9cf1f6c8-8e40-11e6-9095-caac26fb8513.png)

**Comment by meredithrouse** [comment]
SYS-4038
