### ISSUE TITLE
Give: Saved payment accounts not visible on Android

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#1415]
## Steps to Reproduce

FWIW, I'm experiencing this on Android production build

When I add a payment account, i choose save, and name it, but it doesn't appear in my payment account list, though it does appear saved within Rock. When I sign out or force close the app, all of the previously invisible saved accounts then show up.

1. On Android App, give now while signed in, using a new payment account
2. Try to give again and switch payment accounts in order to use the recently saved account

### Buggy Behavior

The new card is not present in the account list, even though it is listed in Rock.

### Expected Behavior

When I new card is added, it should be immediately available and visible within all components that display saved payment accounts.

### Screenshots

Screenshots of the issue are greatly appreciated.

**Comment by johnthepink** [comment]
@jonhorton I wonder if that's true on all platforms. I have noticed some lagginess in things coming back from Rock. Like it does, but might take a few minutes.

**Comment by jonhorton** [comment]
@johnthepink  Looks likes this also happens on my.newspring when adding a new account. It doesn't auto update the change payment screen until I refresh or visit another section and return.
