### ISSUE TITLE
Storybook Meteor Problems

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Holtzman#1418]
Currently, when you try to add a story for a component that imports meteor (`import { Meteor } from "meteor/meteor"`), Storybook has no idea how to do that.

I tried using https://github.com/luisherranz/meteor-imports-webpack-plugin, but ran in to some errors. I don't think that's idea anyways.

I also tried creating a webpack alias to the meteor package, but I'm running in to some issues with `Package` being undefined.

We could fix this issue by passing `Meteor.userId()` and the like as props to stateless components, but we are currently using the Meteor object everywhere.

I'm hoping there's a webpack config way to fix this.

**Comment by dcs619** [comment]
Maybe [this](https://github.com/thereactivestack/meteor-webpack/issues/194) would work?

**Comment by jbaxleyiii** [comment]
fixed with https://github.com/NewSpring/Holtzman/pull/1451
