### ISSUE TITLE
node-sass listed twice in package.json

### ISSUE THREAD

**Issue by delianides** [NewSpring/Holtzman#1429]
`flow-typed` doesn't like that`node-sass` is listed twice in package.json. As a [dependency](https://github.com/NewSpring/Holtzmann/blob/master/package.json#L77) and as a [dev dependency](https://github.com/NewSpring/Holtzmann/blob/master/package.json#L154).

**Comment by dcs619** [comment]
Yep, I got the same error.  I checked with James and removed it from dependencies on my branch.
