### ISSUE TITLE
Discuss the impact of moving away from modals

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#1465]
I wanted to propose potentially moving away from modals for integral components (giving / sign in/up) in favor of full pages / urls for each step of the process.

- This would require us to work in a better routing system to always direct the user to the right place after going to an action that is currently in the modal.
- This would allow us to better track conversion rates on the steps of giving within analytics (Currently can't gather data on this in Hotjar or Google Analytics)
- Would prevent the scrolling that we’ve seen with a small amount of users
- This would also give users specific pages to land on and solidify the process required for certain actions like giving.

Obviously, this would require changes to the patterns that exist, so that users have a clear path to navigate back to where they were. I can potentially see a need for a better subnav in order for this to be possible.

Thoughts on this? What am I missing? Why would this not work? Why are modals better? Help me pick this thought apart—good or bad!

cc: @jbaxleyiii @samclaridge @johnthepink

**Comment by johnthepink** [comment]
We could always add url states to our modals, so that as you are going through checkout, the url changes at each step. I think that would fix the analytics, and the landing page issue without any real design change?
