### ISSUE TITLE
<ProgressBar />

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Holtzman#1519]
```js
<ProgressBar
  title={string}
  total={string}
  percentDone={?number}
  theme={?string = "light" || "dark" } // default dark
  style={?object}
/>
```

Supporting Image:
<img width="293" alt="screen shot 2016-12-01 at 2 55 16 pm" src="https://cloud.githubusercontent.com/assets/4967600/20810080/3683e936-b7d6-11e6-8cb8-eff0e592fd98.png">

**Comment by JakeDawkins** [comment]
Should the background color be a part of the component or the parent?

**Comment by richarddubay** [comment]
@JakeDawkins I'd think that the background color should be set by the parent. Whatever the progress bar is sitting on. Then it could set the theme for this to be light or dark depending on what that color is. @jbaxleyiii ? @samclaridge ?

**Comment by samclaridge** [comment]
As per a slackversation with @JakeDawkins we need to make sure the total doesn't have decimals. We're not sure if this needs to be done on the parent level or not, seeing as we will probably need the full total with decimals for other things. However, in this instance it's an overview and the cleanliness and simplicity lends to it being sans decimals for easier consumption. 

This also brings up the question of whether we would simply omit the decimal or round up or down based on what the figure actually is.
