### ISSUE TITLE
Giving amounts should always show 2 decimal places

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#1534]
## Steps to Reproduce

1. visit my.newspring.cc
2. type in .50

### Buggy Behavior

The system defaults to $.50 instead of keeping the 2nd decimal place.
(The actual total is displayed correctly)

### Expected Behavior

Dollar amounts should always be displayed with 2 decimal places

### Screenshots
![screenshot 2016-12-04 10 35 48](https://cloud.githubusercontent.com/assets/619297/20867241/c98c561c-ba0d-11e6-93ec-557fecc69fa2.png)

PR #1513

**Comment by jbaxleyiii** [comment]
@jonhorton since we can't accept less than $1, how do you want me to handle giving cents?

**Comment by jonhorton** [comment]
@jbaxleyiii Is that still true? I've been able to give $.50 on numerous occasions. 

Nonetheless, this bug is still seems to be present even when giving over a dollar:
![screenshot 2016-12-04 10 41 42](https://cloud.githubusercontent.com/assets/619297/20867276/5e912c2e-ba0e-11e6-8153-3096405d1ab6.png)

**Comment by jbaxleyiii** [comment]
@jonhorton maybe its not with NMI? I could've sworn it was. Regardless, I fix! I fix!

**Comment by jonhorton** [comment]
@jbaxleyiii I vaguely remember that! (So long ago)

Also I should update that expected behavior to is to _only_ show 2 decimal places. Just discovered this is possible:
![screenshot 2016-12-04 10 46 28](https://cloud.githubusercontent.com/assets/619297/20867298/12414560-ba0f-11e6-922f-2e6ab6d3e483.png)

**Comment by jbaxleyiii** [comment]
@jonhorton yep! I pulled back the formatting to be less invasive, but need to set a few more bounds on it!

**Comment by jbaxleyiii** [comment]
@jonhorton this is on beta-my.newspring.cc right now

**Comment by jonhorton** [comment]
@jbaxleyiii thoughts on this:

after testing, I'm realizing it may be more helpful to have a qualifier to the expected results: after I leave the input.

Enter an amount on beta-my, like 1.5. It autocorrects to 1.50, leaving me to think I can't type anything else, even though typing 5 again makes the amount 1.55. Stranger still, hitting backspace, makes it 1.50 again instead of 1.5.

I also confirmed what adam saw, where it's not possible to type 1.00 (double zeroes aren't liked for some reason.)

Would it make more sense to have the formatting apply only after a focus change?

**Comment by jbaxleyiii** [comment]
@jonhorton I totally agree. I don't like like formatting as it causes confusion among users. I have to rewire our global input to correctly fire on blur events consistently. This will take me some time to make sure all other components relying on it still work well. For now I'd say let's only strip non numbers and limit to two decimals, we can keep working to make it better but for launch tomorrow I think boundary formatting is better than live formatting that confuses people

**Comment by jonhorton** [comment]
@jbaxleyiii Sounds like a good plan to me! 👍

**Comment by briankalwat** [comment]
@jbaxleyiii also, here:

https://files.slack.com/files-pri/T02535U9D-F3HRVHKAR/pasted_image_at_2016_12_21_04_09_pm.png
