### ISSUE TITLE
Selecting Web as a campus has unexpected results

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#1535]
## Steps to Reproduce

1. Sign into beta-my and visit your profile (Also happens when giving for the first time without a saved payment account)
2. Set your campus as Web
3. Give an amount, and go to the review screen
4. Observe the Campus name

### Buggy Behavior

If Web is your selected campus, the Review screen shows "Central Campus"

![screenshot 2016-12-04 10 50 49](https://cloud.githubusercontent.com/assets/619297/20867319/f4fa692c-ba0f-11e6-8e59-577d678e56a7.png)

If you gave for the first time, then go to edit your person info, the campus field is blank if you had selected Web.

![screenshot 2016-12-04 10 50 36](https://cloud.githubusercontent.com/assets/619297/20867322/fd00aab4-ba0f-11e6-87c8-d7a29a8e497f.png)

### Expected Behavior

Campus should read as Web and not Central if Web is the selected campus.

A person's profile should save the Web selection if that's what they chose when giving for the first time.

### Screenshots

Screenshots of the issue are greatly appreciated.

**Comment by jbaxleyiii** [comment]
@jonhorton you are still the best at QA 😍

**Comment by jbaxleyiii** [comment]
@jonhorton following the steps (both locally and on beta) I haven't been able to reproduce? Can you try and replicate again?

**Comment by jonhorton** [comment]
I can't replicate now :( web shows up in all instances. 

I'm wondering if it has to do with an edge case where a person doesn't have a campus, address, or saved payment. I'll dig a little more and see if I can find it. :heart:
