### ISSUE TITLE
Give with an account CC iPad Mini 9.3.5 (13G36)

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Holtzman#1568]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Give Now
2. Give an amount to General Fund
3. Select "Review Contribution"
4. Select "Complete Gift in Browser"

### Buggy Behavior

Nothing happens once I select "Complete Gift in Browser". It highlights the button green but no actions.

### Expected Behavior

Launch safari to complete payment

### Screenshots

Screenshots of the issue are greatly appreciated.

![img_6773](https://cloud.githubusercontent.com/assets/24526905/21104765/c589dc62-c055-11e6-8dc4-aa9ba28e5b99.PNG)

**Comment by jbaxleyiii** [comment]
fixed in next beta!
