### ISSUE TITLE
Scheduling Giving Displays Success Message that is Unclear/Misleading

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1569]
## Steps to Reproduce

1. Set up a scheduled gift, and date it to start on a future date.

### Buggy Behavior

Upon completion, the messaging thanks you for your contribution, which could make the user think they've been charged - rather than the schedule just being successfully created.

### Expected Behavior

Upon completion, the messaging should thank them for scheduling their giving, and confirm the date they set for the schedule to begin on.

### Screenshots

![img_0061](https://cloud.githubusercontent.com/assets/2465823/21104921/50a9c03c-c056-11e6-8312-a89086127a51.PNG)

**Comment by jbaxleyiii** [comment]
@briankalwat this is fixed in the updates with the dashboard 👍
