### ISSUE TITLE
Helper Text when Cancelling a Giving Schedule has Incorrect Grammar

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1570]
## Steps to Reproduce

1. Cancel a Giving Schedule

### Buggy Behavior

Text reads "to follow up with you regarding this contributions, click here".

### Expected Behavior

Text should read (something to the effect of) "to follow up with you regarding your contributions, click here".

### Screenshots

![img_0004](https://cloud.githubusercontent.com/assets/2465823/21107263/1b290130-c05f-11e6-94ef-a20ef0130dec.PNG)

**Comment by jbaxleyiii** [comment]
fixed in next beta! Thanks!!
