### ISSUE TITLE
Choosing Custom for schedule breaks review.

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzman#1571]
## Steps to Reproduce

1. Go to Give Now tab
2. Enter an amount and choose a fund.
3. Choose "Schedule this Contribution"
4. Choose a frequency
5. Choose "Custom" for the start date and pick a date in the calendar modal.
6. Click "Review Contribution".

### Buggy Behavior

The date and frequency do not show up on the review page. After this, the choices on the Give Now tab for scheduling no longer work correctly. Also, clicking "Custom" again to uncheck it brings the modal calendar back up again.

### Expected Behavior

You should be able to select a custom start date and it should show correctly on the review page and not break the functionality of the schedule pickers.

### Screenshots

<img width="377" alt="screenshot 2016-12-12 11 41 20" src="https://cloud.githubusercontent.com/assets/3229463/21107543/0f9788ea-c060-11e6-8aa5-4f6e4078d810.png">

**Comment by jbaxleyiii** [comment]
fixed!
