### ISSUE TITLE
Fund Breakdown Doesn't Display All Funds

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Holtzman#1599]
## Steps to Reproduce

1. From the Giving Dashboard select 2015 from the Year In Review summary dropdown.

### Buggy Behavior

Fund Breakdown isn't updated to reflect Clemson For Christmas.

### Expected Behavior

All funds, which have a total amount given greater than $0 are displayed.

**Comment by delianides** [comment]
@edolyne are we only displaying the funds the user contributed too?

**Comment by edolyne** [comment]
@delianides After chatting with James it looks like that is where we are going to land on this.
