### ISSUE TITLE
Double Icon Tag

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#1618]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Go to filter history
2. Click start date tag
3. Click out of the cal modal without selecting a date.

### Buggy Behavior
The tag now has 2 icons in it, the cal icon, and the x icon. 

### Expected Behavior
If you close out of the cal modal without selecting a date then the tag should return to it's standard state, light-tertiary background and dark-primary text.

### Screenshots

![screenshot 2016-12-19 15 31 31](https://cloud.githubusercontent.com/assets/7452283/21328081/3cf5d15c-c600-11e6-8eb0-937d4a0509f4.png)

**Comment by jbaxleyiii** [comment]
fixed
