### ISSUE TITLE
Make text clickable for radio buttons

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#1620]
## Steps to Reproduce

1. Try to select a radio button by clicking the label

### Buggy Behavior
Radio button does nothing

### Expected Behavior
Radio buttons should include the text label in the clickable area to make it easier for users to interact with them.

**Comment by samclaridge** [comment]
This is especially important as it will have a direct impact on schedule gift conversions.

**Comment by jbaxleyiii** [comment]
fixed
