### ISSUE TITLE
Indecisive scheduler loses ability to give

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#1621]
## Steps to Reproduce

Describe how to reproduce this issue.

1. On give now, input dollar amount
2. Select schedule radio button
3. Deselect schedule radio button

### Buggy Behavior
The Review Contribution button remains disabled.

### Expected Behavior
When you select to schedule a contribution the button changes from active to disabled, but if you remove the schedule the button does not respond back to being active.

### Screenshots
![screenshot 2016-12-19 16 30 08](https://cloud.githubusercontent.com/assets/7452283/21329767/6bd2f79a-c608-11e6-9081-7849423d3cb7.png)

**Comment by jbaxleyiii** [comment]
fixed
