### ISSUE TITLE
Unsuspecting student removes mothers checking account from dashboard

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#1622]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Go to dashboard
2. Look at your saved account
3. Click red X

### Buggy Behavior
There shouldn't be the red X, should be a green >
You should not be able to delete a saved account from the dashboard.

### Expected Behavior
Clicking the saved account card takes you to the edit screen.

**Comment by jbaxleyiii** [comment]
@samclaridge this was a time concession to get this shipped before EOY. Editing actual payment details requires more heighliner work than we had time this year so this keeps existing functionality. First of next year this will be improved alongside editing schedules. Let's keep this open as a new feature until we add it

**Comment by samclaridge** [comment]
@jbaxleyiii ehh this feels like a really bad user experience though. I honestly did it by accident, there's no verification or indication that clicking that is going to delete the account. I think this will cause major issues. Is there not a way to at least take them to the new screen and just show the delete button?

https://cl.ly/2g0I2C0C0k0T

**Comment by jbaxleyiii** [comment]
Sure that just feels equally broken? I'd rather modal open a confirmation.
Do we have the full edit (including changing payment details designed?).

**Comment by jbaxleyiii** [comment]
fixed
