### ISSUE TITLE
Btn--small brings festive cheer to every hovering mouse

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#1623]
## Steps to Reproduce

1. Go to an active schedule
2. Hover on the alert btn--small

### Buggy Behavior
Button hover background color is green, not red.

### Expected Behavior
hover state colors should match the button color.

### Screenshots
https://cl.ly/0L0J051m0N3s

**Comment by jbaxleyiii** [comment]
fixed
