### ISSUE TITLE
Displaying failed/pending payments (Nexus 7)

### ISSUE THREAD

**Issue by morgansmithh** [NewSpring/Holtzman#1631]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Give Now with expired, or wrong ACH /CC. This should give you a error message. Exit out 
2. Go to home sub-nav and view activity feed 

### Buggy Behavior

Failed/pending payments showing up in Activity feed incorrectly. It is showing up as a white card and no "X" icon. No link to fix the problem.

### Expected Behavior

Card should be red. Text should be white. "X" icon in upper left. Link to fix the problem. 

![screen shot 2016-12-20 at 11 41 13 am](https://cloud.githubusercontent.com/assets/22217299/21359161/48e76472-c6a9-11e6-9556-d5960dbfa01a.png)

**Comment by morgansmithh** [comment]
Allison had same issue with Iphone 6+

**Comment by morgansmithh** [comment]
I'm sure if failed payments were showing, they would have an X icon

**Comment by dcs619** [comment]
On iOS (iPad) I'm showing a failed payment, but no X icon and the `Contact Us` text is smashed too close together. 

![img_0041](https://cloud.githubusercontent.com/assets/1210933/21359061/e33fec98-c6a8-11e6-8548-90d07d1ef425.PNG)

**Comment by richarddubay** [comment]
@jbaxleyiii Correct me if I'm wrong, but I don't think the cards are supposed to be red with the "X" icon in the history feed. The red card should just show on the Activity feed on the Home tab, right?

**Comment by richarddubay** [comment]
The spacing in the copy for the failed transaction mentioned above will be fixed by https://github.com/NewSpring/Holtzman/pull/1650

**Comment by jbaxleyiii** [comment]
@edolyne let's update these docs

**Comment by edolyne** [comment]
Sounds good, I'll make the changes.

On Tue, Dec 20, 2016 at 8:20 PM, James Baxley <notifications@github.com> wrote:
@edolyne [https://github.com/edolyne] let's update these docs

**Comment by edolyne** [comment]
I've gone ahead and updated the documentation to reflect the Failed Transaction card in Giving History
