### ISSUE TITLE
Add an Account timeout?

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Holtzman#1634]
## Steps to Reproduce

Describe how to reproduce this issue.

1. While logged in, go to Saved Accounts and click Add Account.
2. Go through the process of adding your address and card number, then Add.
3. If the card number is bad/invalid, the UI doesn't time out (or at least hadn't timed out after 60 seconds).
4. Mash buttons in frustration.
5. ??????
6. PROFIT

### Buggy Behavior

The `Saving Account` UI that pops up never shows an error or a helpful timeout message.

### Expected Behavior

Some sort of timeout after ¿20? seconds, or read the failure message for the card if it's returned.

This behavior was tested on an iPad, but usability applies to other devices as well.

**Comment by allisonkring** [comment]
this is happening on the iPhone 6+ as well
