### ISSUE TITLE
Radio goo goo, radio gah gah

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#1636]
### Expected Behavior

Radio button labels should be ```soft-half-left``` so the text is closer to the radio button. 
Radio button labels should also become ```text-dark-primary``` when the radio is active and checked.

**Comment by richarddubay** [comment]
@samclaridge Can you put up an image of what this should look like, please? I just want to make sure I'm on the right track. Thanks!

**Comment by richarddubay** [comment]
Before:
<img width="249" alt="screenshot 2016-12-20 15 28 23" src="https://cloud.githubusercontent.com/assets/3229463/21366750/23beb414-c6c9-11e6-93af-9d7288a491d5.png">

After:
<img width="254" alt="screenshot 2016-12-20 15 28 30" src="https://cloud.githubusercontent.com/assets/3229463/21366752/2647e692-c6c9-11e6-8b31-c7efcc2d9af4.png">

Is this right?

**Comment by richarddubay** [comment]
If the above is right, it is fixed by https://github.com/NewSpring/Holtzman/pull/1652

**Comment by samclaridge** [comment]
@richarddubay looks like a winner to me
![](https://media2.giphy.com/media/ukhC4gaVV99de/giphy.gif)
