### ISSUE TITLE
Select arrow color protesting 2016

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#1638]
## Steps to Reproduce

1. Go to giving dashboard
2. View the year select

### Buggy Behavior
Dropdown arrow is dark-tertiary

### Expected Behavior

Dropdown arrow should be light-primary, or take the light/dark props if we're using it here.

### Screenshots

![screenshot 2016-12-20 11 03 40](https://cloud.githubusercontent.com/assets/7452283/21357737/53138f48-c6a4-11e6-9bde-0d8b8b2ef942.png)

**Comment by richarddubay** [comment]
This will be fixed by https://github.com/NewSpring/Holtzman/pull/1656
