### ISSUE TITLE
Inputting amount on iOS requires too many taps

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Holtzman#1640]
## Steps to Reproduce

Describe how to reproduce this issue.

1. On an iOS device, go to Give Now.
2. Tap the amount input
3. Tap the keyboard `123` to input an amount.

### Buggy Behavior

The native keyboard pops up as a QWERTY keyboard.

### Expected Behavior

On tap of the amount input, the native keyboard should pop up as a number pad.

**Comment by jbaxleyiii** [comment]
@dcs619 we do that because native iOS number pad won't allow you to enter cents 👎. It sucks but until react-native, we can't access the number + `.` keyboard
