### ISSUE TITLE
Try Again button on iOS giving doesn't do anything

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Holtzman#1641]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Give Now with a new/saved account on iOS
2. Redirect to giving in browser
3. Tap Give Now
4. The gift will fail with an incorrect account
5. Click the `Try Again` button under "Uh Oh!"
6. Nothing happens

### Buggy Behavior

Nothing happens.

### Expected Behavior

Something would happen, the screen would refresh, or the loading state will pop up for a moment.

**Comment by JakeDawkins** [comment]
@jbaxleyiii what should happen here?

**Comment by jbaxleyiii** [comment]
hmmm, @JakeDawkins it should take you back to the app
