### ISSUE TITLE
Sign In button doesn't have lock icon

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Holtzman#1643]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Sign out/incognito window to Give Now
2. Look at the Sign In button

### Buggy Behavior

`Sign In` is all by itself.  

![](https://media.giphy.com/media/l41Yko95OitJfzBJe/giphy.gif)

### Expected Behavior

According to the docs, the Sign In button should have a lock icon next to it.

**Comment by samclaridge** [comment]
@dcs619 the docs must be wrong then.

Lock for Sign In was never in the designs.

![screenshot 2016-12-20 11 41 42](https://cloud.githubusercontent.com/assets/7452283/21359178/5d351c8a-c6a9-11e6-9aa3-26069e7f46ed.png)

**Comment by dcs619** [comment]
@samclaridge ¯\_(ツ)_/¯

This is the design I'm testing against:

![image](https://cloud.githubusercontent.com/assets/1210933/21359362/0eebb52e-c6aa-11e6-8cb0-572e232a3bc9.png)

**Comment by samclaridge** [comment]
@jbaxleyiii do you know why/where this got added? It doesn't make sense to me for it to be here.

**Comment by jbaxleyiii** [comment]
@samclaridge it was a bug that I fixed on the native build but haven't deployed to beta-my. I bet @edolyne saw it on the build and added it to the doc. Regardless, this is fixed (just not deployed to beta-may.

Thanks @dcs619!

**Comment by morgansmithh** [comment]
@jbaxleyiii I put this in the google doc for Nexus 7 as well, unless you'd like me to put Pass and remove the lock button from the documentation

**Comment by jbaxleyiii** [comment]
@morgansmithh lets hold off on a pass in the docs until yall can rereview it 👍
