### ISSUE TITLE
iOS: schedule display missing "No More Contributions"

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Holtzman#1644]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Sign in to your account on an iOS device.
2. Find an active schedule and tap details
3. Scroll to the bottom to view transactions

### Buggy Behavior

Nothing is displayed at the bottom of the transaction list.

### Expected Behavior

According to the docs, there should be a message `No More Contributions` at the bottom of the list.

**Comment by allisonkring** [comment]
this is also happening on an iPhone 6+

**Comment by jbaxleyiii** [comment]
@dcs619 @allisonkring this is a mistake in the docs actually (I've commented on them!) We load in all transactions from a schedule at once
