### ISSUE TITLE
iOS: Give as Guest "Give Using" button

### ISSUE THREAD

**Issue by allisonkring** [NewSpring/Holtzman#1648]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Enter amount to give, fund
2. Click give as guest, enter all personal info>next>enter billing info>next> enter card info>next
3. Click "Complete Gift in Browser"

### Buggy Behavior

There is no green "Give Using" button that displays last 4 and appropriate account type

### Expected Behavior

should display green "Give Using" button that displays last 4 and appropriate account type

### Screenshots

https://photos.google.com/photo/AF1QipMJ_I6s8GyBGBRUEuJTWYZyWewULEYleR_i1uMu

**Comment by allisonkring** [comment]
James just said that this is how this works with Apple products but we need to make sure we document this :)

**Comment by jbaxleyiii** [comment]
ping @edolyne for updating docs
