### ISSUE TITLE
Filter Transactions On Smaller Screens

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Holtzman#1655]
## Steps to Reproduce

1. Navigate to Giving History
2. Click Filter
3. Select some filter options
4. Press Filter Transactions

### Enhancement

On smaller screens, the filter dialog covers the majority of the screen, making it hard to realize that the transactions have actually been filtered.  On smaller screens, we should potentially hide the Filter accordion when Filter Transactions is clicked.

**Comment by samclaridge** [comment]
I would push for this to be default behavior as the filter is even pretty large for desktop. So on submit using the ``` Filter Results ``` button, the filter would close to show you the newly filtered results. We also are planning to a add a remove filters button in the filter bar as well.
