### ISSUE TITLE
Font Weight Doesn't Reset to Heavier Weight When Going Back From Devotional

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1660]
## Steps to Reproduce

1. Select a Study from the Home Feed
2. Select an Entry From the Study
3. Go Back to the Study from the Devotional

### Buggy Behavior

Heading font weight changes from heavy to thin when viewing devotional, but does not switch back when going back to the study.

### Expected Behavior

Heading font weight should only be thin when viewing a devotional (when the devo/scripture switcher is present.

### Screenshots

![img_0099](https://cloud.githubusercontent.com/assets/2465823/21392781/7e77c7d8-c75f-11e6-9689-07e4267422ce.PNG)
![img_0100](https://cloud.githubusercontent.com/assets/2465823/21392780/7e763148-c75f-11e6-8df4-1ed6225abbde.PNG)
![img_0101](https://cloud.githubusercontent.com/assets/2465823/21392779/7e74986a-c75f-11e6-8321-97764838a239.PNG)

**Comment by jbaxleyiii** [comment]
fixed
