### ISSUE TITLE
Description Formatting on Giving Activity Cards with Multiple Funds Missing Space

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1661]
## Steps to Reproduce

1. View Giving Activity Feed

### Buggy Behavior

Cards with multiple fund gifts have no space between the last fund listed and the rest of the sentence in the description.

### Expected Behavior

Description for multiple fund gift cards should be a correctly formatted sentence.

### Screenshots

![img_0102](https://cloud.githubusercontent.com/assets/2465823/21393657/6a3d5608-c763-11e6-917f-e3f7d39b30da.PNG)

**Comment by allisonkring** [comment]
this is also on the iPhone 6+
