### ISSUE TITLE
One Time Schedules that are Completed Listed Under "Active Schedules"

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1662]
Talked w/James about this - just wondering if we can make it more clear somehow. My initial thought is it doesn't make sense to include schedules that are completed in the "Active Schedules" section. If, as a user, i'm not going to be charged further - I wouldn't consider that to be an "active" schedule since it has in fact run its course.

Open for discussion! 🚀

**Comment by richarddubay** [comment]
@briankalwat I agree with you. The word "active" makes me think it's current and ongoing, not a past thing. Is there another place that currently exists for people to see completed schedules?

**Comment by samclaridge** [comment]
I agree. I don't think the dashboard is the place for completed schedules. The goal of the page is to give you the overview of your giving health. This doesn't line up with completed schedules.

We currently don't have any other place for completed schedules. Do you think this is something we need? Technically you would be able to get to the finished schedule page via the transaction in history. I'm wondering if this is enough to satiate that requirement, or if we need something more?

**Comment by briankalwat** [comment]
I'm thinking if we can eventually make schedules their own page, we can have active first, and then list completed schedules below. The main reason I think it _might_ be helpful to surface them would be if people could have the ability to "resume" a schedule (create a new schedule based on the funds/amounts of a completed/cancelled one).

Thoughts?

**Comment by jbaxleyiii** [comment]
@samclaridge @briankalwat let me run this past finance 👍
