### ISSUE TITLE
Renaming Saved Account Issue When Attempting to Edit Mid-Word

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1665]
## Steps to Reproduce

1. Click on a Saved Account
2. Click Name to Rename
3. Try to delete a letter in the middle of name

### Buggy Behavior

Input will always auto-advance to end of word and force you to relocate your cursor.

### Expected Behavior

Cursor should only go where you put it.

**Comment by meredithrouse** [comment]
SYS-3965
