### ISSUE TITLE
iOS: Header does not stay at top of screen when scrolling

### ISSUE THREAD

**Issue by allisonkring** [NewSpring/Holtzman#1668]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Click on Devotional
2. Click on Study
3. Scroll down to see header disappear

### Buggy Behavior

Header does not stay at top when you scroll down

### Expected Behavior

Header should stay at top of screen when scrolling

### Screenshots
![header scrolling](https://cloud.githubusercontent.com/assets/24681860/21398240/a71db9ee-c774-11e6-95b4-8f394d97cf90.JPG)

Screenshots of the issue are greatly appreciated.

**Comment by briankalwat** [comment]
Also replicated on iPhone 7 Plus.

**Comment by jbaxleyiii** [comment]
This is actually wrong in the docs! So no worries!
