### ISSUE TITLE
Adding Saved Accounts: Not Sure "Verifying Account" Language is the Best

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1669]
When a user adds an account, is there any actual verification going on? I was able to successfully add the same card multiple times including once with a fake ccv number, once with an expiration date from 2015, etc.

If those checks aren't in place, maybe we should use "Saving Account" until they are, so they user doesn't assume they can rely on our verification as confirmation that they entered the information correctly.

**Comment by jbaxleyiii** [comment]
@briankalwat I'd prefer to make it actually verify! I'll look into why it isn't doing this!
