### ISSUE TITLE
"Going Public" Study Does Not Have an Image

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1671]
## Steps to Reproduce

1. View Studies Feed and scroll to "Going Public"

### Buggy Behavior

Study does not have an image.

### Expected Behavior

All studies should have images.

### Screenshots
![img_0103](https://cloud.githubusercontent.com/assets/2465823/21401129/0e6ee238-c781-11e6-99a9-ed1dd2d9c709.PNG)

**Comment by briankalwat** [comment]
Just created this so we didn't forget to do whatever it is that we need to to regenerate the image.

**Comment by jbaxleyiii** [comment]
@briankalwat so turns out the web images were BIGGER THAN 24MB which killed our shrinking util. I manually fixed them so web is now actually usable and the app has the image
