### ISSUE TITLE
Devotional Images Are Cut Off on Initial Load

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1672]
## Steps to Reproduce

1. View any entry in the "30 Ways to Pray" Study

### Buggy Behavior

Inline image is initially cutoff (swiping horizontally reveals the full image).

### Expected Behavior

Image should be fully in view and not cut off.

### Screenshots

![img_0104](https://cloud.githubusercontent.com/assets/2465823/21401772/8d4b1b88-c783-11e6-89cb-0eb57ffc8654.PNG)

**Comment by jbaxleyiii** [comment]
@briankalwat I was afraid of this 😢. It'll happen for content near the bottom as well. This will be a hard fix
