### ISSUE TITLE
Switching Study/Series Page Cards to be Consistent w/Devotional/Sermon Page Cards

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1674]
@sam @jbaxleyiii just putting this here for future reference.

I think the white cards look a lot cleaner, and the outline on them should still be enough to separate them off the background for series that have white as an actual series color.

## Potentially switching these cards:

![study_720](https://cloud.githubusercontent.com/assets/2465823/21402799/1d44ef62-c788-11e6-8290-a0ba46677d31.jpg)

## to be consistent with these cards:

![devotional__study_entry__720](https://cloud.githubusercontent.com/assets/2465823/21402804/23e5028a-c788-11e6-92ce-dc4842a3637e.jpg)

**Comment by jbaxleyiii** [comment]
Should we do this on series as well?

**Comment by briankalwat** [comment]
@jbaxleyiii my thought was yes - what do y'all think?

**Comment by meredithrouse** [comment]
SYS-4040
