### ISSUE TITLE
Schedule Details Formatting Issue at Anchored Breakpoint

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1675]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Click "View Schedule Details" on any schedule that is giving to multiple funds.

### Buggy Behavior

Funds formatting looks off with indentations.

### Expected Behavior

Funds should be aligned in a straight list.

### Screenshots

Screenshots of the issue are greatly appreciated.
![image](https://cloud.githubusercontent.com/assets/2465823/21403220/d977e85a-c789-11e6-9226-0c9e8685cd61.png)

**Comment by jbaxleyiii** [comment]
fixed
