### ISSUE TITLE
Active Schedules Cards are Rounding Down Total

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1676]
## Steps to Reproduce

1. Click on "View Schedule Details" for the following schedule.

https://beta-my.newspring.cc/give/schedules/f0db7e3b0c95948e8fd3a8e9cfe3906cbb4b3416049afec61d9b2d8bb49f9d0c

### Buggy Behavior

Schedule is for 2 funds for a total of $1.05, but Active Schedule card only says $1.00

### Expected Behavior

Active Schedule card total should be accurate.

### Screenshots

![image](https://cloud.githubusercontent.com/assets/2465823/21403859/a2b182ba-c78c-11e6-83c4-a92a6cf4f2d8.png)

![image](https://cloud.githubusercontent.com/assets/2465823/21404003/2b3d51ea-c78d-11e6-8f4d-b7bd0aef81f7.png)

**Comment by jbaxleyiii** [comment]
fixed
