### ISSUE TITLE
Mobile Web: Registering for account from Give Now opens from bottom (full screen) not left

### ISSUE THREAD

**Issue by morgansmithh** [NewSpring/Holtzman#1686]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Go to Give Now sub-nav while signed out
2. Click Register

### Buggy Behavior

Register modal opens from bottom and takes up whole screen 

### Expected Behavior

Register modal opens from left

**Comment by JakeDawkins** [comment]
I might be misunderstanding, but I believe this is intended behavior. I think the only places that the modal should slide out from the side is on desktop
