### ISSUE TITLE
App Search for Web Missing

### ISSUE THREAD

**Issue by JakeDawkins** [NewSpring/Holtzman#1705]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Open my.newspring.cc in a browser
2. Click on discover

### Buggy Behavior

The search bar isn't present. Its a hold out from long term tech debt with the app launch.

### Expected Behavior

The search bar should be present and active

### Screenshots

![screen shot 2017-01-05 at 1 26 46 pm](https://cloud.githubusercontent.com/assets/9259509/21692485/1b133306-d34b-11e6-92fc-d2e68e53e85a.png)

**Comment by meredithrouse** [comment]
SYS-4019
