### ISSUE TITLE
Main nav should show on dashboard mount

### ISSUE THREAD

**Issue by JakeDawkins** [NewSpring/Holtzman#1712]
## Steps to Reproduce

Describe how to reproduce this issue.

1. While watch live banner is present, go to the giving dashboard
2. Click multiple tabs on the dashboard
3. Open the watch live banner
4. Go back to the dashboard using the back button on the screen.

### Buggy Behavior

The nav with the back button is still present, until you nav back through all the tabs you previously pressed.

### Expected Behavior

When returning from the video player, the `didMount` of the dashboard should reset the nav to the main nav

**Comment by meredithrouse** [comment]
SYS-4037
