### ISSUE TITLE
Sermon/Series/Devotional Redirects for Universal Links

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1778]
We recently added functionality for Comms to be able to redirect an older series or sermon to a newer series or sermon on the same topic, in order to direct our people to our freshest content.

In the [template code](https://github.com/NewSpring/NewSpring/blob/master/assets/_source/templates/global/_fieldgroups.group/sermons-collection.html#L77), it's checking for a **closed** status + `collection_series` (for redirecting series) or `entry_sermon` (for sermons), and if an entry has been selected in either of those fields, it redirects to it - otherwise business as usual.

I'm assuming those fields are also available via GQL, so i'm hoping we can replicate that functionality in the app.

**Comment by briankalwat** [comment]
Now that I'm thinking about this, we're also doing this for old devotional links, pointing them to their corresponding studies.

https://github.com/NewSpring/NewSpring/blob/master/assets/_source/templates/global/_fieldgroups.group/editorial-entry.html#L20

**Comment by richarddubay** [comment]
@jbaxleyiii This would be important for deep links correctly going where they need to go.

**Comment by meredithrouse** [comment]
SYS-4039
