### ISSUE TITLE
iOS Discover Page: Hero ad doesn't open to page

### ISSUE THREAD

**Issue by morgansmithh** [NewSpring/Holtzman#1822]
## Steps to Reproduce

1. Click on discover 
2. Click on the "leading image"/ hero 

### Buggy Behavior

When you click on the hero, the screen doesn't change but remains on the discover screen

### Expected Behavior

When you click on the ad/hero, it should take you to the page that the ad/hero is advertising.

**Comment by richarddubay** [comment]
Sure enough, I can reproduce. Looks like the links are trying to go to the page on my.newspring (which obviously won't work).

 ![](https://media2.giphy.com/media/3o7abCb5Nv2mqw4a76/giphy.gif)

**Comment by briankalwat** [comment]
Still an issue in latest beta 5.0.17 (50039).

**Comment by briankalwat** [comment]
@JakeDawkins 👍 💯
