### ISSUE TITLE
Update NewSpring logo for alerts.

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#1897]
The NewSpring logo should be updated to be white on a green background. Currently it is a green logo, with a white n, on a black background.

**Current:**
![2017-05-25 16 20 08](https://cloud.githubusercontent.com/assets/7452283/26468991/76a19a26-4166-11e7-82a7-3b9d876c8279.png)

**To be updated to this:**
<img width="327" alt="screenshot 2017-05-25 16 23 43" src="https://cloud.githubusercontent.com/assets/7452283/26469021/8ddc8d0e-4166-11e7-93b3-7396a5d27edf.png">

**Comment by jbaxleyiii** [comment]
done!
