### ISSUE TITLE
Incorrect copy in Group Finder

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1899]
### Buggy Behavior

Copy is incorrect.

### Expected Behavior

Should say "Groups You Lead" and "Find Your People".

### Screenshots

![image uploaded from ios](https://cloud.githubusercontent.com/assets/19376946/26470055/4ce7a320-416a-11e7-9cc8-d5d0159ee872.jpg)

**Comment by jbaxleyiii** [comment]
Fixed!
