### ISSUE TITLE
Show grayed out picture for no group picture

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1900]
### Buggy Behavior

Could be interesting to put a generic gray picture if the group does not have a picture to encourage people to upload one. Maybe it could even so "No picture" or "Upload photo". Can they upload a photo straight from the card? Just some thoughts :)

### Expected Behavior

Describe what should actually happen.

### Screenshots

![image uploaded from ios](https://cloud.githubusercontent.com/assets/19376946/26470178/c262d516-416a-11e7-8ec4-27ae39d6c738.jpg)

**Comment by jbaxleyiii** [comment]
@meredithrouse I think this is a great idea! And a potential improvement for our minicard. However I think it is out of scope for 5.2.0. Lets create a story for mini card improvement though!

> move to JIRA
