### ISSUE TITLE
Dividing line should be 1px

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#1901]
### Current

Dividing line between tags and search on Group Finder is 2px.

### Expected
Dividing line between tags and search on Group Finder should be 1px.

### Screenshots
![2017-05-25 16 56 29](https://cloud.githubusercontent.com/assets/7452283/26470298/2cf14458-416b-11e7-8470-c2e1433c659c.png)

**Comment by jbaxleyiii** [comment]
fixed!
