### ISSUE TITLE
NewSpring logo cut off

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1903]
### Buggy Behavior

The sign-in page does not fit the screen.

### Expected Behavior

Be able to see everything.

### Screenshots

![image_uploaded_from_ios_720-2](https://cloud.githubusercontent.com/assets/19376946/26470426/a4de910a-416b-11e7-92b7-bdd468ea6db1.jpg)

**Comment by jbaxleyiii** [comment]
This is also caused by #1910. Closing for that one!
