### ISSUE TITLE
Gray out "Enter" when no password is present

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1904]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Type in email in login screen.
2. Do not type a password.
3. Hit enter.

### Expected Behavior

Would expect that "Enter" is grayed out or you get an error message when you don't enter a password.

### Screenshots

![image_uploaded_from_ios_720-2](https://cloud.githubusercontent.com/assets/19376946/26470519/f8f44956-416b-11e7-83c9-4ada1f3b0868.jpg)

**Comment by jbaxleyiii** [comment]
fixed!
