### ISSUE TITLE
Cannot go back when entering a new payment

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1905]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Login.
2. Go to giving dashboard.
3. Scroll down to bottom and add new payment.
4. Try to hit back button.
5. Get stuck and shed a tear.
6. If you tap it twice it works.

### Buggy Behavior

Cannot go back when entering a new payment.

### Expected Behavior

Be able to go back easily.

### Screenshots

![image_uploaded_from_ios_720](https://cloud.githubusercontent.com/assets/19376946/26470553/1eb89d4a-416c-11e7-9928-eb894ae8a02d.jpg)

**Comment by jbaxleyiii** [comment]
fixed!
