### ISSUE TITLE
Add "Give Feedback" button

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1906]
### Expected Behavior

We want to make it easy for our beta testers to give feedback :) I think we only want this to be in the beta app, but I'd ask James for clarity.

### Screenshots

![image_uploaded_from_ios_720](https://cloud.githubusercontent.com/assets/19376946/26470847/323f379c-416d-11e7-956c-79883149a1dd.jpg)

**Comment by jbaxleyiii** [comment]
Done!
