### ISSUE TITLE
Pre-log user in to Group leader toolbox

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1907]
###Steps to Reproduce

1. Login
2. Tap on Group Finder
3. Select "View Leader Toolbox"
4. See screenshot.

### Expected Behavior

When I click "View leader toolbox" I want to be able to immediately be able to view the toolbox without having to click Login in the top right corner.

### Screenshots

![img_0012](https://cloud.githubusercontent.com/assets/19376946/26471082/2b8a5ef8-416e-11e7-8c80-8cb50d777dcd.PNG)

**Comment by jbaxleyiii** [comment]
fixed!
