### ISSUE TITLE
Top entries switch places after refreshing

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1908]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Login
2. Navigate to home feed
3. Swipe down to refresh a couple of times
4. Top 2 entries switch place

### Expected Behavior

Entries stay in the same place.

### Screenshots

![img_0530](https://cloud.githubusercontent.com/assets/19376946/26474251/f31ad5f6-417d-11e7-81e5-18ddfc8be2b0.PNG)

![img_0529](https://cloud.githubusercontent.com/assets/19376946/26474259/f6fad388-417d-11e7-9936-7ac5b3aaeca6.PNG)

**Comment by jbaxleyiii** [comment]
@JakeDawkins and I looked at this today actually! The two entries have the exact same time in the database! So unless we add on another sorting method, this can happen. I'm fine to leave it as a known edge case for now as the fix would require some larger changes in sorting
