### ISSUE TITLE
"View leader toolbox" button still grayed after leaving toolbox

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1909]
## Steps to Reproduce

1. Click leader toolbox
2. Click Done in top left corner
3. Notice the button is stilled grayed out

### Buggy Behavior

Have to click off of button to get it to go back to white.

### Expected Behavior

Button would not still look selected; button would be white.

### Screenshots

![img_0533](https://cloud.githubusercontent.com/assets/19376946/26474367/a1012986-417e-11e7-94c0-adb986be04fa.PNG)

**Comment by jbaxleyiii** [comment]
fixed!
