### ISSUE TITLE
Change toolbox button language

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1918]
### Expected Language

Next Steps would like to change "View Leader Toolbox" to "Manage My Group."

### Screenshots

![img_0564](https://user-images.githubusercontent.com/19376946/26930910-ce49230e-4c2c-11e7-8d5b-d32fe5d4e116.PNG)

**Comment by samclaridge** [comment]
My understanding behind the terminology was because it matched what was in Rock. If we make this change do we also need to change it in Rock?

**Comment by meredithrouse** [comment]
Let me ask Pudge and I'll let you know!

**Comment by meredithrouse** [comment]
@samclaridge @jbaxleyiii Pudge made a good point that it does not say Group Leader Toolbox on the page that shows you your groups in Rock. It's more of just an internal phrase that we use.

**Comment by samclaridge** [comment]
@meredithrouse Ok sounds good. I'm cool to change it, I just want to make sure whatever language we use is consistent across the board to avoid confusion. #clarity
