### ISSUE TITLE
my.newspring.cc in production and beta dont match app

### ISSUE THREAD

**Issue by allisonkring** [NewSpring/Holtzman#1920]
## Steps to Reproduce

Describe how to reproduce this issue.

1. In Chrome Desktop, go to beta-my.newspring.cc or my.newspring.cc
2. Go to Sections Tab
3. observe that tiles dont match what is actually in the beta app :)

### Buggy Behavior

The tiles under Sections tab dont match the actual app

### Expected Behavior

They should match :)

### Screenshots

Screenshots of the issue are greatly appreciated.
beta-my.newspring.cc
![screen shot 2017-06-08 at 1 18 40 pm](https://user-images.githubusercontent.com/24681860/26941750-984bd370-4c4d-11e7-8797-3856df263379.png)

Beta app on IOS
![img_2489](https://user-images.githubusercontent.com/24681860/26941762-a0e24028-4c4d-11e7-808d-378690167a71.PNG)

**Comment by richarddubay** [comment]
@allisonkring I feel like that was on purpose. I'm sure @jbaxleyiii knows for sure, but the one on beta-my was meant to resemble the menu on newspring.cc I think.

**Comment by samclaridge** [comment]
@richarddubay yeah that's on purpose because we don't have desktop interfaces for a lot of the corresponding places. The desktop version is centered around giving, with nod toward where we are heading based on the app.

Hope that helps!
