### ISSUE TITLE
Download giving statement

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Holtzman#200]
@samclaridge do we have the print / download icon?

This is the UI trigger + the retrieval of the file in Rock.

**Comment by samclaridge** [comment]
We did. But, it doesn’t match any of our new icons… so I’m redoing them now.

Samuel Claridge

— Sent from
https://polymail.io/

On Wed, Feb 24, 2016 at 10:36 PM James Baxley

<
mailto:James Baxley <notifications@github.com>
> wrote:

https://github.com/samclaridge
do we have the print / download icon?

This is the UI trigger + the retrieval of the file in Rock.

—

Reply to this email directly or
https://github.com/NewSpring/Apollos/issues/200
.

https://github.com/NewSpring/Apollos/issues/200
