### ISSUE TITLE
Add support for selecting a default payment account

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Holtzman#441]
This will need a corresponding change in Rock to add either an `Order` field or a `IsDefault` boolean. Either way, this would need to be a field that triggers changes to other saved payments attached to a person.

Thoughts @dcs619 @benwiley?

**Comment by dcs619** [comment]
Adding an Order property would follow the pattern already used in
Rock.Model, and relatively easy to implement.

That would be my recommendation.

**Comment by jbaxleyiii** [comment]
@dcs619 awesome. I'll chat with Frank to see when we could get it in a sprint

**Comment by jbaxleyiii** [comment]
@samclaridge not that we need to do it, but if we had an order field, we could add a drag and drop reorder UI

**Comment by dcs619** [comment]
![](https://media.giphy.com/media/msKNSs8rmJ5m/giphy.gif)

**Comment by meredithrouse** [comment]
Moved to JIRA. SYS-3867.
