### ISSUE TITLE
Add ability to add saved accounts without a purchase and edit accounts

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Holtzman#442]
@samclaridge thoughts on UI for adding and editing? They will need to enter all payment details (personal, billing, and payment fields) like a regular transaction.

They should be able to edit the name on the card, the order / default status, and potentially the expiration date. Assume yes to edit expiration and if I discover else wise I'll let you know

**Comment by briankalwat** [comment]
@jbaxleyiii oooo ooo oo me me me pick me! :dancer: :boom: :100:

**Comment by samclaridge** [comment]
@jbaxleyiii we have the pattern for this here:

https://www.dropbox.com/s/ljyl9g56sg6ydcz/Screenshot%202016-03-22%2011.00.34.png?dl=0

Samuel Claridge

— Sent from
https://polymail.io/

On Tue, Mar 22, 2016 at 10:58 AM Brian Kalwat

<
mailto:Brian Kalwat <notifications@github.com>
> wrote:

https://github.com/jbaxleyiii
oooo ooo oo me me me pick me!
