### ISSUE TITLE
Adjust give sentence colors

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#490]
I just read through the blog post explaining the new give app and I wondered if we should update the colors if people are having an issue seeing the $0.00 due to contrast.

Here is my proposed solution:
• Update active description text from dark-tertiary to dark-primary
• Update inactive description text from light-tertiary to dark-tertiary
• Update active selects or inputs from dark-primary to primary
• Update inactive selects or inputs from light-tertiary to dark-tertiary

![fig 1](https://photos-6.dropbox.com/t/2/AABaBEtmh3YlW0EGlK1henArHJ1UeA92Og8am24Li_Hxxw/12/5045573/png/32x32/3/1460059200/0/2/Screenshot%202016-04-07%2011.22.15.png/ELe_4wMYl6sEIAEgAigB/oUfFdNT5kpXxkqC_r3fLCOaTENFOg6w5w4t0LzfINig?size_mode=3&size=1280x960)
![fig 2](https://photos-3.dropbox.com/t/2/AAD2SOzY6okZfEVGwl1CchvjNmpBvb1CMFGzS8trBpi4YA/12/5045573/png/32x32/3/1460059200/0/2/Screenshot%202016-04-07%2011.22.52.png/ELe_4wMYl6sEIAEgAigB/9S8itiskw1FD7bDqfCS5WeLDt07WOvgA0sf3kQEEvLY?size_mode=3&size=1280x960)

**Comment by jbaxleyiii** [comment]
@samclaridge can you repost the images? I tried what you sent but I'm afraid it removes the clarity around not having to fill in the second half of the form / disabled states?

**Comment by samclaridge** [comment]
@jbaxleyiii 

![screenshot 2016-04-07 11 22 15](https://cloud.githubusercontent.com/assets/7452283/14768508/5987d4aa-0a12-11e6-93f9-4063053f12b8.png)

![screenshot 2016-04-07 11 22 52](https://cloud.githubusercontent.com/assets/7452283/14768511/69a48a40-0a12-11e6-95bb-eadad5ce7c22.png)

**Comment by jbaxleyiii** [comment]
@samclaridge 👍 I did it wrong haha. I'll adjust to that
