### ISSUE TITLE
Update Last Login on every session

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#508]
Since we encourage users to stay logged in, I thought it could be a good feature to update the last login date in Rock on every new session.  This would make our active user report more accurate. Thoughts?

**Comment by jbaxleyiii** [comment]
@jonhorton I love it. I actually have it built to hook into Rocks active user system but there is a blocking API bug on rocks end that if we fix, we can get currently online status and oage views. Probably a half day fix for spark
