### ISSUE TITLE
Sticky Scrolling

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Holtzman#619]
We should investigate the scrolling in the home feed and other places to see why it feels sticky.

Scrolling in a single devotion is a good example of the faster scrolling we probably want.

I imagine this is a CSS thing.

**Comment by johnthepink** [comment]
I was able to get native-ish scrolling by nesting our Global template with some divs and css, much like you so on our devotion page. But, we need to do some React render optimizations before we want to turn this on.

**Comment by johnthepink** [comment]
We may be able to try this again because of changes in #671

**Comment by jbaxleyiii** [comment]
@johnthepink this would be awesome to get before launch

**Comment by johnthepink** [comment]
@jbaxleyiii adding to the milestone

**Comment by jbaxleyiii** [comment]
cc @jonhorton per our convo today
