### ISSUE TITLE
Back Button Intermittently Has Issues

### ISSUE THREAD

**Issue by delianides** [NewSpring/Holtzman#657]
I haven't been able to determine if the issues are because the app is processing a request and prevents the back button from working or if the touch event for the back button just isn't firing. More information would be helpful and can be added here.

**Comment by johnthepink** [comment]
I have noticed this as well. I just increased our tap target size in #659, so let's see if the issue persists on the next build we do.

**Comment by johnthepink** [comment]
The best reproduction step I have found is scrolling to the bottom of some content, and then it doesn't work. Maybe to do with margin on the bottom of a div covering the nav?

**Comment by johnthepink** [comment]
I can confirm this happens on all albums that have track lists that you must scroll to see.

**Comment by briankalwat** [comment]
@delianides @johnthepink I just reproduced this while viewing an entry from giving history. iPhone 7 Plus, iOS 10.0.1.
