### ISSUE TITLE
Scripture API Call

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Holtzman#730]
I'm thinking we should move the scripture call to Heighliner, cache the data, and return it through the GQL query for devos. Currently, it's just a Meteor method.

We should also check to make sure there aren't any caching restrictions in the API terms of use.

**Comment by jbaxleyiii** [comment]
@johnthepink want to have this be your first addition to the rebuilt heighliner?

**Comment by johnthepink** [comment]
@jbaxleyiii sounds good

**Comment by johnthepink** [comment]
This has been added to Heighliner now https://github.com/NewSpring/Heighliner/pull/86

**Comment by johnthepink** [comment]
Heighliner has the ability to make the scripture API call for us now, but I think we still need to update the content resolver to return the scripture data, instead of just the book and passage.

I'll leave this open, because once that's done we will need to update the app to use the data from Heighliner instead of making the call directly.
