### ISSUE TITLE
Receipt POST to Rock should include a batch

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Holtzman#754]
The current [POST](https://github.com/NewSpring/Apollos/blob/master/apollos/give/observers/transactions.js#L102) doesn't include a Batch.  See [here](https://github.com/SparkDevNetwork/Rock/issues/1608) why it's important. Sometime in the future this field will be required.

I'd recommend editing [FinancialTransactions.Post](https://github.com/NewSpring/Rock/blob/master/Rock.Rest/Controllers/FinancialTransactionsController.Partial.cs#L68) to assign a default batch to transactions, but you could also request a new batch specifically based on the card or payment type (this may be something finance would like).

**Comment by jbaxleyiii** [comment]
@dcs619 this is great to know! I'll get this added next week!

**Comment by jbaxleyiii** [comment]
@dcs619 any thoughts on how to best do batching? I don't want to create a batch per transaction

**Comment by dcs619** [comment]
Rock already creates a batch for each day, so I would edit the REST controller to default to the current day's batch.  The only thing to watch out for is on Sunday, since you'd want to exclude any batches from check scanning/specific services.

Would it be helpful to see how finance processes/closes batches?

**Comment by jbaxleyiii** [comment]
yeah that would be great. I've got a meeting with them tomorrow afternoon so I'd love to be able to bring intelligent questions. This will be shipping this week btw

**Comment by dcs619** [comment]
@jbaxleyiii [Here's](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/FinancialBatchService.Partial.cs#L91) the method I would call.  The daily batch name is `CEN [Date] Mail` so we could use the same pattern or use a new batch name `CEN [Date] Web`.  The first time that Get method is called for the day would create a new batch, then use the existing batch on subsequent calls.

**Comment by jbaxleyiii** [comment]
@dcs619 well thats freaking awesome! I'll work on integrating that in!

**Comment by jbaxleyiii** [comment]
@dcs619 so this api doesn't exist yet does it?

**Comment by dcs619** [comment]
You might be able to use OData to pull it from `api/FinancialBatches` where Name = `CEN [Date] Web`.  

Otherwise we can 1) create a `api/FinancialBatches/[name]` endpoint to get the default batch ID or 2) edit [FinancialTransactions.Post](https://github.com/NewSpring/Rock/blob/master/Rock.Rest/Controllers/FinancialTransactionsController.Partial.cs#L68) to assign a default batch.
