### ISSUE TITLE
Use datepicker for filtering giving history

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#805]
I think it'd be more consistent to use a date picker when setting dates to filter giving history results. It was a little confusing when going to set that but only getting a text input.

https://www.dropbox.com/s/s7j1x25ssu5fixb/Screenshot%202016-07-24%2009.10.29.png?dl=0

**Comment by samclaridge** [comment]
@jonhorton we opted to use the text field for now for 2 main reasons.

1. Our current date picker UI isn't ideal and needs some love that we haven't had time to give it.

2. Also, our current date picker implementation is actually a modal, so in this scenario you end up with a modal over a filter dropdown, which gets pretty messy. 

3. We estimated the amount of clicks or taps to select the year/month using the date picker vs typing the numbers is actually very similar. 

I don't disagree that we should eventually move to using a date picker, but it didn't seem like the best decision for right now given the current constraints and added time needed to redo our date picker component.

**Comment by jonhorton** [comment]
@samclaridge Thanks for the clarity on that decision! It makes a lot of sense for those reasons.

I came across a really nice date picker option in the past week (that I can't remember) that made it really easy to select past years/months. I can draw it up later in person, and when I find it, I'll save a link!
