### ISSUE TITLE
List detail animation from music player

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzman#836]
If you click **\* from the Music Player the animation is weird because it has to close the Music Player modal and then open the List Detail view, which is also a modal. 

Not sure what the best solution is, but it needs some love.

**Comment by johnthepink** [comment]
Do we think we can handle this in this milestone?

**Comment by samclaridge** [comment]
From the proposed solutions, I think I'd rather go down the route of removing the modals. The functionality we have created goes beyond what the terminology and limitations of a modal implies.

My gut is this is more than we can handle for this milestone, although I don't know for sure.

If we do shelve it for this release, I do think we should revisit it in the not too distant future though, as I think we are going to quickly run into this limitation again.

**Comment by johnthepink** [comment]
Ok. I'll defer to @jbaxleyiii, but I'd be in favor of moving this our of this milestone.
