### ISSUE TITLE
Devo Inline content Image

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Holtzman#839]
We used to pull images from the content for devo's header image in the feed. This doesn't seem to be working now.

Example: "Don't Follow The Rules": https://alpha-app.newspring.io/devotions/98547d83af9e355b264e42c13689890b

<img width="410" alt="screenshot 2016-07-27 15 56 19" src="https://cloud.githubusercontent.com/assets/816517/17190125/af46cf46-5412-11e6-9d55-a2ea449985e5.png">

**Comment by meredithrouse** [comment]
SYS-3960
