### ISSUE TITLE
 Pagination resets when going back from other page

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzman#841]
**Steps to Reproduce**
I've been able to reproduce this on desktop + mobile/beta app
- Visit group finder, search for a tag
- Scroll to bottom and load more results
- Click on any group past the 10 results mark (from the loaded results)
- Click to back to the search results list

Buggy Behavior
- The results resets to only show the initial 10 results (confirmed by the 10 of ## groups text)
- This happens regardless of how many times you click load more results

Expected Behavior
- Clicking back takes you to the spot you left off in the list instead of resetting the results

**Comment by jbaxleyiii** [comment]
@jonhorton thanks for the great bug report as always!

@johnthepink or anyone else who is interested in this one. I'd like to hold off with this until the new react-apollo integration is done here. Then we can use the pagination support which will be more efficient for the client AND fix this issue

**Comment by briankalwat** [comment]
I don't think this is limited to just group finder. When I come back to the home feed from a piece of content that is fairly buried, it usually brings me back up towards the bottom of the first set of things that are initially loaded.

**Comment by jbaxleyiii** [comment]
This is fixed 👍
