### ISSUE TITLE
splash screen doesn't look great on tablet

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Holtzman#922]
<img width="581" alt="screenshot 2016-09-04 08 42 09" src="https://cloud.githubusercontent.com/assets/4967600/18231053/7d4c8ab2-727b-11e6-8283-cbb2d8f1ac73.png">
<img width="581" alt="screenshot 2016-09-04 08 42 09" src="https://cloud.githubusercontent.com/assets/4967600/18231055/87fc11d0-727b-11e6-8f5c-16d2ab65c965.png">

**Comment by johnthepink** [comment]
Yea I noticed that too. It does for the most part work, but maybe we can play with positioning based on bottom or center?

**Comment by johnthepink** [comment]
New images added in #941, but leaving this open for now because we need to handle weird sized tablets better.

**Comment by meredithrouse** [comment]
SYS-4084
