### ISSUE TITLE
Home Feed: Intermittently Fails to Load Content as User Scrolls

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#994]
## Steps to Reproduce

I haven't figured out what exactly is triggering this to happen, but I've had the iPhone 5s on 9.3.5 (13G36) on 3 different occasions now, while scrolling in the home feed, it has failed to load additional content and instead leaves the placeholder components in the app shell. Will update if this behavior is prevalent on other devices.
### Buggy Behavior

While scrolling through the home feed, all content disappears and is replaced by placeholder components.
### Expected Behavior

Content should continue to load consistently for as long as the user continues to scroll/remain on the home feed.
### Screenshots

![img_0003](https://cloud.githubusercontent.com/assets/2465823/18486865/edf1bf0c-79c0-11e6-9b12-1eb002546c68.PNG)

**Comment by richarddubay** [comment]
@briankalwat I can't seem to make this happen with the 5S. I wonder if there is a certain set of steps we could take to duplicate?
